apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: demo-voting-app
    name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: postgres-pod
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          # in real world, we would not hardcode the credentials here and instead use secrets
          # postgres requires a user and password to be set up when the container is created, so we use environment variables
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
