apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
    name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: vote-result-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: vote-result-pod
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
