apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: demo-voting-app
    name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: vote-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: vote-pod
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
