apiVersion: v1
kind: Service
metadata:
  name: db # this is the name of the service and matches container name as the source code is configured to look for a service named db in postgres connection string
  labels:
    name: db
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
