apiVersion: v1
kind: Service
metadata:
  name: redis # source code is configured to look for a service named redis in redis connection string, so we need to name the service redis here (also good practice to name the service same as the container name)
  labels:
    name: redis
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: demo-voting-app
    name: redis-pod
