apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - port: 80 # port exposed by the service
      targetPort: 80 # port exposed by the container for result-service
      nodePort: 30003 # port exposed by the node to access the service
  selector:
    app: demo-voting-app
    name: vote-result-pod
