apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80 # port exposed by the container for result-service
      nodePort: 30003
  selector:
    app: result-service
