apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: demo-voting-app
    name: vote-pod
