apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 80 # port exposed by the container for vote-service
      nodePort: 30004
  selector:
    app: vote-service
